### ISSUE TITLE
NPM Install error

### ISSUE THREAD

**Issue by neo-art** [stackbit/stackbit-theme-azimuth#26]
Hi All,

Thank you for the nice theme and great service.
Trying to install the project locally following the instruction from the Stackbit cms:
```
git clone https://github.com/neo-art/bulh-azimuth-5821c.git
cd bulh-azimuth-5821c
git checkout preview
npm install
npm run start
```
Unfortunately during `npm install` I've got an error and I can't continue.
Googled it but couldn't find a working solution so hoped you can have some clue what causes this.
Attaching the debug log.
[2021-04-26T17_17_38_427Z-debug.txt](https://github.com/stackbit/stackbit-theme-azimuth/files/6378964/2021-04-26T17_17_38_427Z-debug.txt)

Thank you in advance.

**Comment by smnh** [comment]
Looks like a node version mismatch.
Probably the libsass module version locked in package-lock.json doesn't work with node you have locally.
Try updating the module in package.json, or using node 10

**Comment by neo-art** [comment]
> Looks like a node version mismatch.
> Probably the libsass module version locked in package-lock.json doesn't work with node you have locally.
> Try updating the module in package.json, or using node 10
Thank you for the response. 
Yes I installed nodejs with homebrew - the latest version 16.0.0 I believe.
It would be easier to update the module in packaje.json (hopefully it will work) but I can't locate
which line on is nodejs located. Any hint? :)

**Comment by smnh** [comment]
Changing node.js version will require installing something like [nvm](https://github.com/nvm-sh/nvm).
But in your case I would suggest updating the dependencies in `package.json` to their latest versions.
Run `npm outdated` and update all dependencies to their latests versions.
Note, that it might require changing some code on the way to be compatible with newer versions.

**Comment by neo-art** [comment]
Thank you for this.
Heh looks like no fast solution :) and I was thinking I will save some time by using prebuilt themes with Stackbit ;)
A long list of dependencies - definitely something will get wrong :)

**Comment by neo-art** [comment]
Unfortunately, it didn't work :(

**Comment by neo-art** [comment]
Installed NVM, changed the NODE version to 10.24.1 but still can't get there.
`npm run develop` generates a new debug log (attached, this time it is shorter). Any clue what else is wrong?

[2021-04-27T09_43_09_105Z-debug.txt](https://github.com/stackbit/stackbit-theme-azimuth/files/6383887/2021-04-27T09_43_09_105Z-debug.txt)

**Comment by neo-art** [comment]
Decided to remove this project and start from scratch but with HUGO. Hopefully I won't have the same issues. Thank you for the assistance.

**Comment by smnh** [comment]
> Installed NVM, changed the NODE version to 10.24.1 but still can't get there.
> `npm run develop` generates a new debug log (attached, this time it is shorter). Any clue what else is wrong?
> 
> [2021-04-27T09_43_09_105Z-debug.txt](https://github.com/stackbit/stackbit-theme-azimuth/files/6383887/2021-04-27T09_43_09_105Z-debug.txt)
> 
> PS: Downgraded NODEJS to 10.13.0 - still the same

did you try to remove node_modules from previous installation and running `npm install` again with new node version before runnging gatsby develop?

**Comment by neo-art** [comment]
I did few times, cleared cache, removed modules, tried different NODE 10.x.x versions - no luck
